[extension "codex_code_selected"]
	path = codex_code_selected
	url = git@github.com:zj18610273107/codex_code_selected.git
[extension "c_processing"]
	path = c_processing
	url = git@github.com:zj18610273107/c_processing.git
